version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ventureforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ventureforge
      REDIS_URL: redis://redis:6379
      GOOGLE_API_KEY: AIzaSyCeaXYO6RHiFy4YmVGnaN7qXMwm7Qt1bSQ
    depends_on:
      - postgres
      - redis
    command: python scripts/backend_api.py

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
